import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import Header from "@/components/custom/header";
import Footer from "@/components/custom/footer";
import { ThemeProvider } from "@/components/custom/theme-provider";
import { dark } from "@clerk/themes";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
    appearance={{
      baseTheme: dark,
    }}
  >

    <html lang="en" 
    suppressHydrationWarning={true}
    >
      <body
      
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >


              <Header/>
              <main className="min-h-screen">
        {children}
              </main>
              <Footer/>
          </ThemeProvider>

      </body>
    </html>
    </ClerkProvider>
  );
}
